# Generated by Django 5.2.4 on 2025-07-31 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBreachRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('breach_risk_label', models.CharField(blank=True, max_length=20, null=True)),
                ('breach_risk_score', models.IntegerField(blank=True, null=True)),
                ('paste_count', models.IntegerField(default=0)),
                ('last_paste_timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BreachSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('email_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_summaries', to='breach.emailbreachrecord')),
            ],
        ),
        migrations.CreateModel(
            name='BreachMetricIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('email_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='breach.emailbreachrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExposedBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('domain', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('password_risk', models.CharField(max_length=100)),
                ('references', models.TextField(blank=True, null=True)),
                ('searchable', models.CharField(max_length=10)),
                ('verified', models.CharField(max_length=10)),
                ('xposed_data', models.TextField()),
                ('xposed_date', models.CharField(max_length=10)),
                ('xposed_records', models.IntegerField()),
                ('email_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposed_breaches', to='breach.emailbreachrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExposedDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level2_name', models.CharField(max_length=255)),
                ('email_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposed_data', to='breach.emailbreachrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExposedDataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='breach.exposeddatacategory')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy_to_crack', models.IntegerField()),
                ('plain_text', models.IntegerField()),
                ('strong_hash', models.IntegerField()),
                ('unknown', models.IntegerField()),
                ('email_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_strengths', to='breach.emailbreachrecord')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyBreachStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
                ('email_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_stats', to='breach.emailbreachrecord')),
            ],
        ),
    ]
