# Generated by Django 5.2.4 on 2025-07-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='opt',
            new_name='otp',
        ),
    ]
